title: Someone Changed Her Mind, a book by Fran Gale
description: New book release of 2022
author:
  name: Fran Gale,
  email: w.patrick.gale@gmail.com,
  url: https://schm-website.vercel.app/about-me/
